#!/bin/bash

# Run this script in your main Cactus directory:
#   ./utils/Docker/make/image-cpu/run-container-cpu
# This opens a shell running in a container using a Docker image with
# all Cactus dependencies installed.

set -euo pipefail

# <https://stackoverflow.com/questions/242538/unix-shell-script-find-out-which-directory-the-script-file-resides>
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
echo $SCRIPTPATH

home="$HOME"
workdir=$(pwd)
docker build --file "$SCRIPTPATH/make-image-cpu/Dockerfile.run" --build-arg gid=$(id -g) --build-arg home="$home" --build-arg uid=$(id -u) --build-arg username=$(id -n -u) --build-arg workdir="$workdir" "$SCRIPTPATH" --tag runme:cpu

hostname=$(hostname)-docker:cpu
docker run --interactive --hostname "$hostname" --mount "type=bind,source=$home,target=$home" --mount "type=bind,source=$workdir,target=$workdir" --rm --tty --workdir "$workdir" runme:cpu bash
