
#include <stdio.h>

#include "cctk.h"

int BaikalX_Banner(void) 
{
    printf("BaikalX: another Einstein Toolkit thorn generated by\n");
    printf("\n");
    printf("ooooo      ooo ooooooooo.   ooooooooo.                 88\n");
    printf("`888b.     `8' `888   `Y88. `888   `Y88.             888888  \n");
    printf(" 8 `88b.    8   888   .d88'  888   .d88' oooo    ooo   88\n");
    printf(" 8   `88b.  8   888ooo88P'   888ooo88P'   `88.  .8'\n");
    printf(" 8     `88b.8   888`88b.     888           `88..8'\n");
    printf(" 8       `888   888  `88b.   888            `888'\n");
    printf("o8o        `8  o888o  o888o o888o            .8'\n");
    printf("                                         .o..P'\n");
    printf("  NRPy+: Python-based Code Generation    `Y8P'\n");
    printf("   for Numerical Relativity... and Beyond!\n");
    printf(" - homepage: http://blackholesathome.net\n");
    printf(" - download: https://github.com/zachetienne/nrpytutorial\n");
return 0;
}
